name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up go 1.23.4
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4
    
    - name: Build
      run: go build -o go-web-app

    - name: Test
      run: go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug Go version
      run: go version

    - name: Debug Go environment
      run: go env

    - name: Debug Go module files
      run: cat go.mod && cat go.sum

    - name: Clean Go module cache
      run: go clean -modcache

    - name: Install dependencies
      run: go mod tidy

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
        verbose: true
        flags: "--print-resolved-config --issues-exit-code=0"

    - name: Debug output of golangci-lint
      run: cat .golangci-lint.log || echo "No additional logs found"

  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.sha }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      env:
        RUN_ID: ${{ github.run_id }}
      run: |
        sed -i "s/tag:.*/tag: \"${RUN_ID}\"/" helm/go-web-app-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "alwinaji717@gmail.com"
        git config --global user.name "retr0717"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push